<?php require_once 'include/header.php'; ?>
<div class="container">   
<br>
	<div class="row">
	   <div class="col-sm-12 to_animate" data-animation="fadeInLeftBig">
               <h2>Wedding Dress</h2><br>
 <div align="center">

<table border="0" width="95%" cellspacing="0" cellpadding="0">
	<tr>
            <td width="200px"><img src="images/wedding_dress_1.jpg"> </td>
            <td valign="top"><h4>Wedding Dress 1</h4> 
                some description's
                <br> ............ .............. ...........
                ............ .............. ...........
                ............ .............. ...........
                ............ .............. 
                ............ .............. ...........
                <br> ............ .............. ...........
                ............ .............. ...........
                ............ .............. ...........
                <br>
                <p align="right">read more...</p> 
            </td>
	</tr>
        <tr>
            <td colspan="2" align="center" height="60"><img src="images/icon-pre.png"></td>
		</tr>
                <tr>
            <td width="200px"><img src="images/wedding_dress_2.jpg"> </td>
            <td valign="top"><h4>Wedding Dress 1</h4> 
                some description's
                <br> ............ .............. ...........
                ............ .............. ...........
                ............ .............. ...........
                ............ .............. 
                ............ .............. ...........
                <br> ............ .............. ...........
                ............ .............. ...........
                ............ .............. ...........
                <br>
                <p align="right">read more...</p> 
            </td>
	</tr>
        <tr>
            <td colspan="2" align="center" height="60"><img src="images/icon-pre.png"></td>
		</tr>
                <tr>
            <td width="200px"><img src="images/wedding_dress_3.jpg"> </td>
            <td valign="top"><h4>Wedding Dress 1</h4> 
                some description's
                <br> ............ .............. ...........
                ............ .............. ...........
                ............ .............. ...........
                ............ .............. 
                ............ .............. ...........
                <br> ............ .............. ...........
                ............ .............. ...........
                ............ .............. ...........
                <br>
                <p align="right">read more...</p> 
            </td>
	</tr>
        <tr>
            <td colspan="2" align="center" height="60"><img src="images/icon-pre.png"></td>
		</tr>
                <tr>
            <td width="200px"><img src="images/wedding_dress_4.jpg"> </td>
            <td valign="top"><h4>Wedding Dress 1</h4> 
                some description's
                <br> ............ .............. ...........
                ............ .............. ...........
                ............ .............. ...........
                ............ .............. 
                ............ .............. ...........
                <br> ............ .............. ...........
                ............ .............. ...........
                ............ .............. ...........
                <br>
                <p align="right">read more...</p> 
            </td>
	</tr>
        
	
</table></div>
           </div></div></div>
<?php require_once 'include/footer.php'; ?>

